services:
  api-prod:
    build: .
    environment:
      - MODEL_STAGE=Production
    ports:
      - "8001:8000"
  api-canary:
    build: .
    environment:
      - MODEL_STAGE=Staging
    ports:
      - "8002:8000"
  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - .nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api-prod
      - api-canary
